### ISSUE TITLE
Across link leads to broken page

### ISSUE THREAD

**Issue by blewisio** [jmstfv/open-expenses#1]
At time of writing, the link for Across (https://blog.acrossapp.com/how-a-2-person-startup-already-uses-28-other-tools/) is an Application Error:

![Screenshot_2020-04-17 Application Error](https://user-images.githubusercontent.com/5720003/79623906-4367db00-80e4-11ea-99d7-b7a1edf76d61.png)

**Comment by jmstfv** [comment]
Hmm, it works now. I think this is not the first time I see their blog throw `5xx`. For now, I will leave the link as is, but if I come across it again (no pun intended), I'll change the link to the archived version instead.

Thanks for the heads up!
