### ISSUE TITLE
Buttondown link is broken

### ISSUE THREAD

**Issue by blewisio** [jmstfv/open-expenses#2]
The link for Buttondown is https://buttondown.email/running-costs, but that URL returns:

>Not Found :(
>Sorry, no idea what you were looking for here.

There's a "Running costs" link in the extended footer that links to "https://www.notion.so/Running-Costs-f29729ded5494272947f656440967cbf" instead.

**Comment by jmstfv** [comment]
I've updated the link. Thanks for the heads up, Brent!
